version: '3'

services:
  django:
    build: ./django
    volumes:
      - ./django:/app
    ports:
      - '8000:8000'
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    command: sh -c "
            python manage.py migrate &&
            python -Xfrozen_modules=off manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
  
  pgadmin:
    build: ./pgadmin
    ports:
      - '7777:80'
    env_file:
      - ./.env.dev

  postgres:
    image: postgres:16.3-alpine
    restart: always
    env_file:
      - ./.env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d bmstu-food -U admin"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 80s 
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
  

  