version: '3'

services:
  django:
    build: 
      context: ./django
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
    - 8000
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    command:  sh -c "python manage.py collectstatic --no-input &&
              python manage.py migrate &&
              gunicorn bmstu_food.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env.prod
  pgadmin:
    build: ./pgadmin
    ports:
      - '7777:80'
    env_file:
      - ./.env.prod
      - ./.env.email

  postgres:
    image: postgres:16.3-alpine
    restart: always
    env_file:
      - ./.env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d bmstu-food -U admin"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 80s 
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
  
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - django
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:

  