# Generated by Django 5.0.6 on 2024-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20240603_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to='upldfile/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='menudetails',
            unique_together={('dish', 'menu')},
        ),
    ]
