# Generated by Django 5.0.6 on 2024-06-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
