# Generated by Django 5.0.6 on 2024-07-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_dish_image_alter_menu_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='foodservice',
            name='type',
            field=models.CharField(choices=[('wending', 'Вендинг'), ('buffet', 'Буфет'), ('cafe', 'Кафе')], max_length=10),
        ),
    ]
