# Generated by Django 5.0.6 on 2024-07-05 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_dish_image_alter_foodservice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='foodservice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.foodservice'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('foodservice', 'date')},
        ),
    ]
