# Generated by Django 5.0.6 on 2024-06-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_remove_order_count_remove_order_dish_order_date_menu_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
    ]
