FROM python:3.11.5-alpine

WORKDIR /app

EXPOSE 8000

ENV APP_HOME=/app/
RUN mkdir $APP_HOME/staticfiles
RUN mkdir $APP_HOME/mediafiles
WORKDIR $APP_HOME

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt